---
- hosts: localhost
  gather_facts: false
  collections:
    - netapp.ontap
  vars_files:
    - global_nas.vars

  tasks:
    - name: Create CIFS volume
      na_ontap_volume:
        state: present
        name: nas_svm_cifs_01
        vserver: nas_svm
        aggregate_name: aggr1_cluster1_01_data
        size: 20
        size_unit: mb
        policy: default
        junction_path: /nas_svm_cifs_01
        volume_security_style: ntfs
        hostname: "{{ PRI_CLU }}"
        username: "{{ PRI_CLU_USER }}"
        password: "{{ PRI_CLU_PASS }}"
        https: true
        validate_certs: false